name: Lambda usecase
on:
  workflow_dispatch:
    inputs:
      do_plan:
        description: "Run terraform plan?"
        required: false
        default: "true"
        type: boolean
      do_apply:
        description: "Run terraform apply?"
        required: false
        default: "false"
        type: boolean
      do_destroy:
        description: "Run terraform destroy?"
        required: false
        default: "false"
        type: boolean
 
jobs:
  terraform:
    name: Use-case-05
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
 
    env:
      TF_VERSION: '1.10'
      AWS_REGION: us-east-1
      ROLE_TO_ASSUME: arn:aws:iam::211125325699:role/Dummay_OIDC_flow
      TF_LOG: DEBUG
      TF_LOG_PATH: log.txt
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
 
    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: ./use-case-05
        output-file: README.md
        output-method: inject
        git-push: "true"
 
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    # - name: Download terraform.tfvars from S3
    #   run: aws s3 cp s3://pavithra-bucket001/vars.tfvars ./Use-case-03/vars.tfvars
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Set up Node js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install  dependencies and create ZIP
      run: |
        cd use-case-05/files/js
        npm install 
        zip -r ../../files/js/image_resizer.zip .

    - name: Terraform Format Check
      run: terraform fmt -recursive
 
 
    - name: Terraform Init
      working-directory: ./use-case-05
      run: terraform init

    - name: Terraform test
      working-directory: ./use-case-05
      run: terraform test -verbose
      continue-on-error: true
 
    - name: Terraform Validate
      working-directory: ./use-case-05
      run: terraform validate

    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
 
    - name: Run tflint
      run: tflint --config=./.tflint.hcl
      continue-on-error: true
      # run: tflint --init && tflint
 
    - name: Install Checkov
      run: |
        python3 -m pip install --upgrade pip
        pip install checkov
 
    - name: Run Checkov Scan
      run: checkov -d ./ --skip-path .github/* --soft-fail
 
    - name: Terraform Plan
      if: ${{ github.event.inputs.do_plan == 'true' }}
      #working-directory: ./use-case-05
      run: terraform plan -refresh-only

    - name: Terraform Apply (manual)
      if: ${{ github.event_name == 'workflow_dispatch' &&  github.event.inputs.do_apply == 'true' }}
      #working-directory: ./mytestnew
      run: terraform apply -auto-approve 

    - name: Terraform destroy (manual)
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.do_destroy == 'true' }}
      #working-directory: ./mytestnew
      run: terraform destroy -auto-approve 

    - name: Terraform logs
      uses: actions/upload-artifact@v4
      with:
        name: Terraform-logs
        path: log.txt
